[package]
description = "A sparse paged vector with lazy page allocation."
authors = ["Evgenii Nekhoroshev evgnekhoroshev@gmail.com"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/evnekdev/pagedvector"
homepage = "https://github.com/evnekdev/pagedvector"
name = "pagedvector"
version = "0.2.0"
edition = "2021"
readme = "README.md"
keywords = ["vector", "sparse", "paged", "memory", "storage"]
categories = ["data-structures"]

[features]
default = []
serde = ["dep:serde"]
bincode = ["serde", "dep:bincode"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
bincode = { version = "2.0", features = ["serde", "alloc"], optional = true }

[dev-dependencies]
proptest = "1"
